In [3]:
print("Hello World")

Hello World


Import Library - Introduction to Numpy

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\muham\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import sys, time

print("Python version", sys.version.split()[0])
print("NumPy version", np.__version__)

Python version 3.13.14
NumPy version 2.5.2


Time Difference between a Standard Python list and a NumPy Array

In [3]:
n = 500

# -------------------------
# Python List
# -------------------------

py_list = list(range(n))

start = time.perf_counter()

for i in range(len(py_list)):
    py_list[i] = py_list[i] * 2

end = time.perf_counter()

print("Time taken for Python list:", end - start, "seconds")
print(py_list)


# -------------------------
# NumPy Array
# -------------------------

np_array = np.arange(n)

start = time.perf_counter()

np_array = np_array * 2

end = time.perf_counter()

print("Time taken for NumPy:", end - start, "seconds")
print(np_array)
print("NumPy array shape:", np_array.shape)

Time taken for Python list: 0.00012069987133145332 seconds
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 

See the above result? Now you know how NumPy operations along with array form plays a significant role in carrying out calculations efficiently. Imagine programs having much larger arrays with the requirement of carrying out a lot of calculations. 

Let's now create different types of array in NumPy

In [4]:
from_list = np.array([90,80,79,70,60,50,40,30,20,10])
from_3d = np.array([[[3,4,8], [3,4,8], [3,4,8]], [[3,4,8], [3,4,8], [3,4,8]], [[3,4,8], [3,4,8], [3,4,8]]])
print("From 3d:", from_3d)
print(from_3d.dtype)
print(from_3d.shape)

From 3d: [[[3 4 8]
  [3 4 8]
  [3 4 8]]

 [[3 4 8]
  [3 4 8]
  [3 4 8]]

 [[3 4 8]
  [3 4 8]
  [3 4 8]]]
int64
(3, 3, 3)


Arange Function (np.arange(x)) for creating NumPy arrays in an ascending powers of x.

In [5]:
Sequence_1 = np.arange(10)
print(Sequence_1)
print(Sequence_1.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


Linspace Function (np.linspace(min, max, x)) for creating NumPy array having equally spaced x number of elements from min to max

In [6]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

*nD Arrays*

In [7]:
zero_d = np.array(42) # Zero-dimensional array
print("Zero D:", zero_d)
print("Zero D shape:", zero_d.shape)
print("Zero D dimension:", zero_d.ndim)

Zero D: 42
Zero D shape: ()
Zero D dimension: 0


In [8]:
one_d = np.array([42, 43, 44]) # one-dimensional array
print("one D:", one_d)
print("one D shape:", one_d.shape)
print("one D dimension:", one_d.ndim)

one D: [42 43 44]
one D shape: (3,)
one D dimension: 1


In [9]:
two_d = np.array([[1, 2, 3], [4, 5, 6]]) # two-dimensional array
print("two D:", two_d)
print("two D shape:", two_d.shape)
print("two D dimension:", two_d.ndim)

two D: [[1 2 3]
 [4 5 6]]
two D shape: (2, 3)
two D dimension: 2


In [10]:
three_d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # three-dimensional array
print("three D:", three_d)
print("three D shape:", three_d.shape)
print("three D dimension:", three_d.ndim)

three D: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
three D shape: (2, 2, 3)
three D dimension: 3


In [11]:
four_d = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]]) # four-dimensional array
print("four D:", four_d)
print("four D shape:", four_d.shape)
print("four D dimension:", four_d.ndim)

four D: [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
four D shape: (2, 2, 2, 3)
four D dimension: 4


In [16]:
I = np.eye(5,5, 1, dtype=np.int32, order='C')
print("identity:\n", I)

identity:
 [[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
